services:
  - type: web
    name: umami
    env: docker
    plan: free
    branch: master
    dockerfilePath: docker-compose.yml
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: umami-db
          property: connectionString

databases:
  - name: umami-db
    plan: free
